// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleETicketPlatform.Infrastructure.Data;

#nullable disable

namespace SimpleETicketPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240720142104_ShoppingCart")]
    partial class ShoppingCart
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SimpleETicketPlatform.Infrastructure.Data.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Actor identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasComment("Actor biography");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Actor full name");

                    b.Property<string>("ProfilePictureURL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Actor profile picture URL");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasComment("Actor entity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Leonardo DiCaprio is a renowned American actor and film producer, born on November 11, 1974, in Los Angeles, California. He gained fame with his roles in \"Titanic\" (1997) and \"Romeo + Juliet\" (1996) and is known for his versatility and intense performances. DiCaprio has starred in numerous critically acclaimed films, including \"The Wolf of Wall Street,\" \"Inception,\" and \"The Revenant,\" for which he won an Academy Award for Best Actor. Beyond acting, he is an active environmentalist, advocating for climate change awareness and sustainability through his Leonardo DiCaprio Foundation.",
                            FullName = "Leonardo DiCaprio",
                            ProfilePictureURL = "https://s2.r29static.com/bin/entry/84e/720x864,85/1884149/image.webp"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Kate Winslet is a celebrated British actress, born on October 5, 1975, in Reading, England. She rose to international prominence with her role as Rose DeWitt Bukater in \"Titanic\" (1997). Known for her versatility and depth, Winslet has delivered powerful performances in films such as \"Eternal Sunshine of the Spotless Mind,\" \"The Reader,\" for which she won an Academy Award for Best Actress, and \"Steve Jobs.\" Winslet is acclaimed for her ability to portray complex characters and has earned numerous awards throughout her career. She is also an advocate for body positivity and various humanitarian causes.",
                            FullName = "Kate Winslet",
                            ProfilePictureURL = "https://cdn.britannica.com/38/130638-050-DBCE19EE/Kate-Winslet.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Michele Morrone is an Italian actor, model, and singer, born on October 3, 1990, in Melegnano, Italy. He gained international fame for his role as Massimo Torricelli in the 2020 film \"365 Days.\" Known for his charismatic screen presence and intense performances, Morrone has captivated audiences worldwide. In addition to acting, he has a successful music career, with his debut album \"Dark Room\" featuring songs from the \"365 Days\" soundtrack. ",
                            FullName = "Michele Morrone",
                            ProfilePictureURL = "https://i.pinimg.com/736x/cb/d2/b3/cbd2b39d8dd9f39f4499aaa21c5af529.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Anna-Maria Sieklucka is a Polish actress, known for her breakout role as Laura Biel in the 2020 film \"365 Days.\" Born on May 31, 1992, Sieklucka garnered attention for her compelling portrayal of a young woman caught in a complex and intense relationship with a mafia boss. Her performance in \"365 Days\" propelled her to international recognition, showcasing her talent for emotive storytelling and on-screen chemistry. Beyond acting, Sieklucka continues to engage audiences with her dedication to her craft and is poised for further success in her career.",
                            FullName = "Anna-Maria Sieklucka",
                            ProfilePictureURL = "https://media.themoviedb.org/t/p/w500/c5Rhg0pewnANvLfx2fDXKTLawTb.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Biography = "Brad Pitt is a highly acclaimed American actor and film producer, born on December 18, 1963, in Shawnee, Oklahoma. Known for his charismatic presence and versatile performances, Pitt has starred in a wide range of successful films. He gained prominence in the early 1990s with roles in \"Thelma & Louise\" and \"A River Runs Through It,\" and solidified his status as a leading actor with iconic performances in \"Fight Club,\" \"Ocean's Eleven,\" and \"Troy.\" Pitt's acting prowess has earned him numerous awards, including an Academy Award for Best Supporting Actor for his role in \"Once Upon a Time in Hollywood.\" In addition to his acting career, Pitt is also a successful film producer, known for his work with Plan B Entertainment.",
                            FullName = "Brad Pitt",
                            ProfilePictureURL = "https://resizing.flixster.com/SAUTcTD8KmznQaWfE7okll09Fgc=/218x280/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/1366_v9_bc.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Biography = "Angelina Jolie is an iconic American actress, filmmaker, and humanitarian, born on June 4, 1975, in Los Angeles, California. Known for her captivating performances and striking beauty, Jolie has starred in a diverse range of films, including \"Girl, Interrupted,\" \"Lara Croft: Tomb Raider,\" and \"Maleficent.\" Beyond her acting career, she is acclaimed for her humanitarian work as a Special Envoy for the United Nations High Commissioner for Refugees (UNHCR), advocating for refugees' rights and global humanitarian issues. Jolie's impact extends beyond entertainment, making her a prominent figure in both Hollywood and humanitarian efforts worldwide.",
                            FullName = "Angelina Jolie",
                            ProfilePictureURL = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Angelina_Jolie_2_June_2014_%28cropped%29.jpg/640px-Angelina_Jolie_2_June_2014_%28cropped%29.jpg"
                        });
                });

            modelBuilder.Entity("SimpleETicketPlatform.Infrastructure.Data.Models.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Cinema identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasComment("Cinema description");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Cinema logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Cinema name");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");

                    b.HasComment("Cinema entity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cinema City is a modern and stylish cinema offering an exceptional movie-going experience. With state-of-the-art projection and sound systems, comfortable seating, and a wide selection of films ranging from the latest blockbusters to indie gems, Cinema1 is the perfect destination for all film enthusiasts.",
                            Logo = "https://cdn.vectorstock.com/i/1000v/38/76/cinema-logo-movie-emblem-template-vector-19873876.jpg",
                            Name = "Cinema City"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cinema World is a premier destination for movie lovers, offering an immersive cinematic experience with the latest in audio-visual technology. Enjoy a diverse selection of films from Hollywood blockbusters to indie favorites in our comfortable, modern theaters. With a range of delicious concessions and exceptional service, Cinema World is the perfect place for an unforgettable movie-going experience.",
                            Logo = "https://as2.ftcdn.net/v2/jpg/02/24/93/07/1000_F_224930739_ucWKbPcRZVWSksyE71jRP9Y5Phhwx92i.jpg",
                            Name = "Cinema World"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cinema1 is the newest addition to the town, offering a state-of-the-art movie-going experience. Featuring the latest in projection and sound technology, Cinema1 provides comfortable seating and a diverse selection of films, from the latest blockbusters to indie favorites. With a modern ambiance, a variety of snacks, and top-notch service, Cinema1 is set to become the town's premier destination for all cinema enthusiasts.",
                            Logo = "https://seeklogo.com/images/C/cinema-film-logo-4400A608DF-seeklogo.com.png",
                            Name = "Cinema 1"
                        });
                });

            modelBuilder.Entity("SimpleETicketPlatform.Infrastructure.Data.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Movie identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CinemaId")
                        .HasColumnType("int")
                        .HasComment("Movie cinema identifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasComment("Movie description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasComment("Movie end date");

                    b.Property<int>("MovieCategory")
                        .HasColumnType("int")
                        .HasComment("Movie category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Movie name");

                    b.Property<string>("PhotoURL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Movie photo URL");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(5,2)")
                        .HasComment("Movie price");

                    b.Property<int>("ProducerId")
                        .HasColumnType("int")
                        .HasComment("Movie producer identifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasComment("Movie start date");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.HasIndex("ProducerId");

                    b.ToTable("Movies");

                    b.HasComment("Movie entity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CinemaId = 1,
                            Description = "\"Titanic\" is a 1997 epic romance and disaster film directed by James Cameron. It tells the poignant love story of Jack Dawson (Leonardo DiCaprio) and Rose DeWitt Bukater (Kate Winslet), two passengers from different social classes who meet and fall in love aboard the ill-fated RMS Titanic. As the ship tragically sinks on its maiden voyage, their love is tested amidst the chaos and calamity, making \"Titanic\" a timeless tale of love, loss, and human resilience.",
                            EndDate = new DateTime(2024, 8, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            MovieCategory = 3,
                            Name = "Titanic",
                            PhotoURL = "https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg",
                            Price = 12.99m,
                            ProducerId = 1,
                            StartDate = new DateTime(2024, 7, 20, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            CinemaId = 1,
                            Description = "\"365 Days\" is a Polish romantic drama film released in 2020, based on the novel by Blanka Lipińska. The story follows Laura Biel, a sales director who is kidnapped by a Sicilian mafia boss named Massimo Torricelli. Massimo gives Laura 365 days to fall in love with him, promising her a life of luxury and passion. The film explores themes of desire, obsession, and power dynamics amidst a backdrop of opulent settings and intense emotions. ",
                            EndDate = new DateTime(2024, 8, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            MovieCategory = 4,
                            Name = "365 Days",
                            PhotoURL = "https://m.media-amazon.com/images/M/MV5BYjY2NzUxNjgtNjJhNy00NTA4LTlmNzItYzQ4MDdjNWYxZjkwXkEyXkFqcGdeQXVyMTEwMTY3NDI@._V1_FMjpg_UX1000_.jpg",
                            Price = 9.99m,
                            ProducerId = 2,
                            StartDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            CinemaId = 2,
                            Description = "Starring Brad Pitt and Angelina Jolie, the story revolves around John and Jane Smith, a married couple who are unaware that they are both secretly highly skilled assassins working for competing agencies. When they are assigned to kill each other, their seemingly ordinary suburban life turns into a high-stakes game of cat and mouse. Packed with witty banter, explosive action sequences, and charismatic performances from its leads, \"Mr. & Mrs. Smith\" blends romance, humor, and thrilling espionage in a captivating and entertaining manner.",
                            EndDate = new DateTime(2024, 9, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            MovieCategory = 1,
                            Name = "Mr. and Mrs. Smith",
                            PhotoURL = "https://m.media-amazon.com/images/M/MV5BYjY2NzUxNjgtNjJhNy00NTA4LTlmNzItYzQ4MDdjNWYxZjkwXkEyXkFqcGdeQXVyMTEwMTY3NDI@._V1_FMjpg_UX1000_.jpg",
                            Price = 14.99m,
                            ProducerId = 3,
                            StartDate = new DateTime(2024, 8, 9, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            CinemaId = 3,
                            Description = "\"The Wolf of Wall Street\" is a 2013 biographical black comedy directed by Martin Scorsese. Starring Leonardo DiCaprio as Jordan Belfort, the film chronicles Belfort's rise and fall as a stockbroker who engages in rampant corruption and fraud on Wall Street. Known for its high-energy storytelling, extravagant lifestyle depictions, and dark humor, the movie delves into themes of greed, excess, and moral ambiguity. With standout performances, particularly by DiCaprio and Jonah Hill, \"The Wolf of Wall Street\" is both a cautionary tale and an entertaining exploration of the excesses of the financial world.",
                            EndDate = new DateTime(2024, 10, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            MovieCategory = 3,
                            Name = "The Wolf of Wall Street",
                            PhotoURL = "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_.jpg",
                            Price = 19.99m,
                            ProducerId = 4,
                            StartDate = new DateTime(2024, 8, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 5,
                            CinemaId = 2,
                            Description = "\"Maleficent\" is a 2014 fantasy film directed by Robert Stromberg. It stars Angelina Jolie as Maleficent, a powerful fairy who becomes vengeful after being betrayed. The film reimagines the classic \"Sleeping Beauty\" tale from Maleficent's perspective, exploring her backstory and the events that led her to curse Princess Aurora. With stunning visuals, a captivating performance by Jolie, and a fresh take on a well-known story, \"Maleficent\" delves into themes of betrayal, redemption, and the complexity of good and evil.",
                            EndDate = new DateTime(2024, 12, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            MovieCategory = 2,
                            Name = "Maleficent",
                            PhotoURL = "https://upload.wikimedia.org/wikipedia/en/5/55/Maleficent_poster.jpg",
                            Price = 7.99m,
                            ProducerId = 5,
                            StartDate = new DateTime(2024, 10, 18, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 6,
                            CinemaId = 2,
                            Description = "\"Inside Out\" is a 2015 Pixar film directed by Pete Docter. It cleverly explores emotions through the story of Riley, a young girl navigating life's challenges with the help of Joy, Sadness, Anger, Fear, and Disgust—personified as characters inside her mind's control center. The film's imaginative concept and heartfelt storytelling delve into the complexities of growing up, memory, and the importance of embracing all emotions.",
                            EndDate = new DateTime(2024, 9, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            MovieCategory = 5,
                            Name = "Inside out",
                            PhotoURL = "https://m.media-amazon.com/images/M/MV5BOTgxMDQwMDk0OF5BMl5BanBnXkFtZTgwNjU5OTg2NDE@._V1_.jpg",
                            Price = 5.99m,
                            ProducerId = 6,
                            StartDate = new DateTime(2024, 7, 30, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("SimpleETicketPlatform.Infrastructure.Data.Models.MovieActor", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasComment("Movie identifier");

                    b.Property<int>("ActorId")
                        .HasColumnType("int")
                        .HasComment("Actor identifier");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MovieActors");

                    b.HasComment("Movie actor entity");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 6
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 6
                        });
                });

            modelBuilder.Entity("SimpleETicketPlatform.Infrastructure.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Actor identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Order email");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("Order user identifier");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasComment("Order entity");
                });

            modelBuilder.Entity("SimpleETicketPlatform.Infrastructure.Data.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Order item identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasComment("Order items amount");

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasComment("Order item movie identifier");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasComment("Order item movie identifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(7,2)")
                        .HasComment("Order ites price");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");

                    b.HasComment("Order item entity");
                });

            modelBuilder.Entity("SimpleETicketPlatform.Infrastructure.Data.Models.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Producer identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasComment("Producer biography");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Producer full name");

                    b.Property<string>("ProfilePictureURL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Producer profile picture URL");

                    b.HasKey("Id");

                    b.ToTable("Producers");

                    b.HasComment("Producer entity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "James Cameron is a renowned filmmaker and producer known for his innovative and influential work in the film industry. Born in 1954, Cameron directed and produced blockbuster hits such as \"The Terminator,\" \"Avatar,\" and \"Titanic.\" His dedication to pushing technological boundaries has earned him multiple Academy Awards, including Best Picture and Best Director for \"Titanic.\"",
                            FullName = "James Cameroon",
                            ProfilePictureURL = "https://media.vanityfair.com/photos/656f89c8710cfd971ca79847/1:1/w_1333,h_1333,c_limit/vf1223-james-cameron.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Tomasz Mandes is a Polish actor, director, and producer known for his work in Polish cinema, contributing significantly to both film and television.",
                            FullName = "Tomasz Mandes",
                            ProfilePictureURL = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi2UgcvhF7fYSMpId7_kKe3gimVzZz3Kha8Q&s"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Arnon Milchan is a prominent Israeli-American film producer known for founding New Regency Productions. His diverse portfolio includes producing hits like \"Mr. & Mrs. Smith,\" \"Pretty Woman,\" and \"The Revenant.\" Milchan's career spans decades, emphasizing his significant impact on Hollywood through successful films and entrepreneurial ventures.",
                            FullName = "Arnon Milchan",
                            ProfilePictureURL = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Arnon_Milchan_%28990040376210205171%29.jpg/640px-Arnon_Milchan_%28990040376210205171%29.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Martin Scorsese is an acclaimed American filmmaker known for his significant contributions to cinema. Born on November 17, 1942, in New York City, Scorsese has directed numerous iconic films, including \"Taxi Driver,\" \"Goodfellas,\" and \"The Departed.\" His distinctive style often explores themes of crime, redemption, and the human condition. As a producer and director, Scorsese's work on \"The Wolf of Wall Street\" (2013) exemplifies his talent for crafting compelling, character-driven narratives. ",
                            FullName = "Martin Scorsese",
                            ProfilePictureURL = "https://cdn.britannica.com/76/156176-050-90A36E79/Martin-Scorsese-2008.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Biography = "Joe Roth is a prominent American film producer, director, and executive, known for his influential role in Hollywood. Born on June 13, 1948, Roth has produced numerous successful films across various genres. He founded Revolution Studios and served as chairman of Walt Disney Studios and 20th Century Fox. His notable productions include \"Alice in Wonderland,\" \"Snow White and the Huntsman,\" and \"Maleficent.\"",
                            FullName = "Joe Roth",
                            ProfilePictureURL = "https://m.media-amazon.com/images/M/MV5BMTgwMDAyNTI0N15BMl5BanBnXkFtZTcwNDY4MDQ4NA@@._V1_.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Biography = "Pixar Animation Studios, founded in 1986 and now owned by The Walt Disney Company, is renowned for revolutionizing animated filmmaking. Based in Emeryville, California, Pixar has consistently set industry standards with groundbreaking computer-generated imagery (CGI) and storytelling prowess. Their films, including classics like \"Toy Story,\" \"Finding Nemo,\" and \"Up,\" combine technical innovation with heartfelt narratives that appeal to audiences of all ages. Pixar's commitment to creativity and excellence has earned them numerous awards and accolades, solidifying their reputation as one of the most influential animation studios in the world.",
                            FullName = "Pixar Animation Studios",
                            ProfilePictureURL = "https://www.artofthetitle.com/assets/sm/upload/es/cz/3z/5g/pixar.jpg?k=1ed92a7b61"
                        });
                });

            modelBuilder.Entity("SimpleETicketPlatform.Infrastructure.Data.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Shopping cart item identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasComment("Shopping cart items amount");

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasComment("Movie identifiers");

                    b.Property<string>("ShoppingCartId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Shopping cart identifier");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("ShoppingCartItem");

                    b.HasComment("Shopping cart item entity");
                });

            modelBuilder.Entity("SimpleETicketPlatform.Infrastructure.Data.Models.Movie", b =>
                {
                    b.HasOne("SimpleETicketPlatform.Infrastructure.Data.Models.Cinema", "Cinema")
                        .WithMany()
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimpleETicketPlatform.Infrastructure.Data.Models.Producer", "Producer")
                        .WithMany()
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("SimpleETicketPlatform.Infrastructure.Data.Models.MovieActor", b =>
                {
                    b.HasOne("SimpleETicketPlatform.Infrastructure.Data.Models.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleETicketPlatform.Infrastructure.Data.Models.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("SimpleETicketPlatform.Infrastructure.Data.Models.OrderItem", b =>
                {
                    b.HasOne("SimpleETicketPlatform.Infrastructure.Data.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleETicketPlatform.Infrastructure.Data.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SimpleETicketPlatform.Infrastructure.Data.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("SimpleETicketPlatform.Infrastructure.Data.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("SimpleETicketPlatform.Infrastructure.Data.Models.Actor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("SimpleETicketPlatform.Infrastructure.Data.Models.Movie", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("SimpleETicketPlatform.Infrastructure.Data.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
